// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Order, OrderData } from "./tables/Order.sol";
import { OrderCounter } from "./tables/OrderCounter.sol";
