// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Position, PositionData } from "./tables/Position.sol";
import { Order, OrderData } from "./tables/Order.sol";
